version: '3.9'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: store_db
      POSTGRES_USER: store_username
      POSTGRES_PASSWORD: store_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DB_NAME: store_db
      DB_USER: store_username
      DB_PASS: store_password
      DB_HOST: db
      DB_PORT: 5433
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume:
  pgadmin_data:

networks:
  app_network:
    driver: bridge